# Includes an icon in the footer for each username you enter
footer-links:
  dribbble: 
  email: webmaster@keep-on-learning.de
  facebook:
  flickr:
  github: keep-on-learning
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: 
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://raw.githubusercontent.com/keep-on-learning/keep-on-learning.github.io/master/images/kol_logo.png

theme: jekyll-theme-slate
